using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace SanayiPazarim.Entity
{
    public class DataInitializer : DropCreateDatabaseIfModelChanges<DataContext>//verileri ekleyeceğimiz kısım.
    {
        protected override void Seed(DataContext context)
        {
            var kategoriler = new List<Category>()
            {
                new Category(){Name = "DEMİR ÇELİK" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "ELEKTRONİK MALZEMELERİ" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "ELEKTRİK MOTORLARI" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "REDÜKTÖR" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "RULMAN, KEÇE VE KAYIŞ" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "HIRDAVAT" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "LAZER KESİM VE PLAZMA ÜRÜNLERİ" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "SANAYİ MAKİNALARI" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "KALIP SANAYİ" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "DİŞLİ SANAYİ" , Description = "Lorem ipsum dolor sit amet."},
                new Category(){Name = "ALÜMİNYUM" , Description = "Lorem ipsum dolor sit amet."}
            };

            foreach (var kategori in kategoriler)
            {
                context.Categories.Add(kategori);
            }
            context.SaveChanges();

            var urunler = new List<Product>()
            {
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-02 21:48:54"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-02 21:48:54"), Image="product-1.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=1},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-02 21:48:54"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-02 21:48:54"), Image="product-2.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=1},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-02 21:48:54"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-02 21:48:54"), Image="product-3.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:13"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-4.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:13"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-5.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:13"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-6.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:13"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-6.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:13"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-7.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:13"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-8.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-9.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-10.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-11.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-12.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-13.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-14.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-15.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-16.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-1.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-2.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-3.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-4.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-5.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-6.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-7.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-8.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-9.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-10.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2},
                new Product(){Name="Lorem ipsum dolor sit amet",ProductCreateTime=DateTimeOffset.Parse("2020-05-03 22:05:56"), ProductFinishedTime =DateTimeOffset.Parse("2020-05-07 21:45:59"), Image="product-11.jpg",Description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut risus urna, mattis in dapibus ac, euismod sed enim. Pellentesque in cursus orci. Nunc nec risus eu turpis ullamcorper placerat. Suspendisse aliquam, elit ut lobortis euismod, felis nisi pretium lectus, et ultrices arcu purus eget libero. Mauris sed enim euismod, volutpat ligula vitae, fermentum orci.",SubDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",CategoryId=2}
            };

            foreach (var urun in urunler)
            {
                context.Products.Add(urun);
            }
            context.SaveChanges();

            base.Seed(context);
        }
    }
}